services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    network_mode: bridge
    environment:
      - GATEWAY_LISTEN=0.0.0.0:4566
      - LOCALSTACK_AUTH_TOKEN=$LOCALSTACK_AUTH_TOKEN
      - DEBUG=${DEBUG:-0}
      - HOSTNAME_EXTERNAL=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  serverless-app:
    container_name: serverless-app
    image: arm64v8/node
    working_dir: /usr/src/app
    volumes:
        - ./projects/aws-node-express-dynamodb-api:/usr/src/app
    entrypoint: /bin/bash
    command: ["-c", "npm install && npm install -g serverless && exec /bin/bash"]
