AWSTemplateFormatVersion: '2010-09-01'
Description: 'Setup for S3 encryption requirement exercise'

Resources:
  SecureUploadsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: secure-uploads
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SecureUploadsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${SecureUploadsBucket.Arn}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'
          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub '${SecureUploadsBucket.Arn}/*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': 'true'

Outputs:
  BucketName:
    Description: Name of the secure uploads bucket
    Value: !Ref SecureUploadsBucket

  BucketArn:
    Description: ARN of the secure uploads bucket
    Value: !GetAtt SecureUploadsBucket.Arn