AWSTemplateFormatVersion: '2010-09-01'
Description: 'Exports VPC and Subnet IDs for use in other stacks'

Parameters:
  VpcId:
    Type: String
    Description: 'ID of the existing VPC'
    Default: 'vpc-123456'  # Assuming this is a placeholder or LocalStack default VPC ID

  PublicSubnet1:
    Type: String
    Description: 'ID of the first public subnet'
    Default: 'subnet-public1'  # Placeholder or example subnet ID

  PublicSubnet2:
    Type: String
    Description: 'ID of the second public subnet'
    Default: 'subnet-public2'  # Placeholder or example subnet ID

  PrivateSubnet1:
    Type: String
    Description: 'ID of the first private subnet'
    Default: 'subnet-private1'  # Placeholder or example subnet ID

  PrivateSubnet2:
    Type: String
    Description: 'ID of the second private subnet'
    Default: 'subnet-private2'  # Placeholder or example subnet ID

# Needed because reasons
Resources:
  PlaceholderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: placeholder-bucket-!Sub "${Environment}-${AWS::StackName}"

Outputs:
  VpcIdExport:
    Description: 'Exported VPC ID'
    Value: !Ref VpcId
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'

  PublicSubnetsExport:
    Description: 'Exported list of Public Subnets'
    Value: !Join [', ', [!Ref PublicSubnet1, !Ref PublicSubnet2]]
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnets'

  PrivateSubnetsExport:
    Description: 'Exported list of Private Subnets'
    Value: !Join [', ', [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnets'
