AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template defines variables (parameters) and outputs them. 
  It does not create any AWS resources.

Parameters:
  Environment:
    Description: "Environment name (e.g., dev, staging, prod)"
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    ConstraintDescription: "Must be dev, staging, or prod."

  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: "Must be a valid EC2 instance type."

  KeyName:
    Description: "Name of an existing EC2 KeyPair to enable SSH access"
    Type: AWS::EC2::KeyPair::KeyName
    Default: test
    ConstraintDescription: "Must be a valid key pair name."

# Needed because reasons
Resources:
  PlaceholderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: placeholder-bucket-!Sub "${Environment}-${AWS::StackName}"

Outputs:
  EnvironmentOutput:
    Description: "The selected environment"
    Value: !Ref Environment

  InstanceTypeOutput:
    Description: "The selected EC2 instance type"
    Value: !Ref InstanceType

  KeyNameOutput:
    Description: "The selected Key Pair name"
    Value: !Ref KeyName
