services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - GATEWAY_LISTEN=0.0.0.0:4566
      # - SERVICES=s3,iam,sqs,sns
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  serverless-app:
    container_name: serverless-app
    image: arm64v8/node
    working_dir: /usr/src/app
    volumes:
        - ./projects/aws-node-express-dynamodb-api:/usr/src/app
    entrypoint: /bin/bash
    command: ["-c", "npm install && npm install -g serverless && exec /bin/bash"]
